- name: Install containerd
  apt:
    name: containerd.io
    state: present

- name: Check the containerd configuration
  ansible.builtin.template:
    src: templates/containerd-config.toml.j2
    dest: /etc/containerd/config.toml
    mode: 0644
  register: containerd_config

- name: Reload containerd if necessary
  ansible.builtin.systemd:
    name: containerd
    state: restarted
  when: containerd_config.changed

- name: Start and enable containerd
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: yes
