- name: Set up containerd
  include_tasks: containerd.yaml

- name: Install kubelet, kubeadm and kubectl
  apt:
    pkg:
    - kubelet={{ kubernetes_version }}-00
    - kubeadm={{ kubernetes_version }}-00
    - kubectl={{ kubernetes_version }}-00

- name: Hold kubelet, kubeadm and kubectl version
  dpkg_selections:
    name: '{{ item }}'
    selection: hold
  with_items:
  - kubelet
  - kubeadm
  - kubectl

- name: Install open-iscsi
  ansible.builtin.package:
    name: open-iscsi

- name: Start iscsid
  ansible.builtin.service:
    name: iscsid
    state: started
    enabled: yes
