galaxy_info:
  author: Mikkel Kroman
  namespace: mkroman
  description: Install weechat on Debian-based systems
  license: Apache-2.0
  min_ansible_version: '2.1'
  platforms:
  - name: Debian
    versions:
    - all
  galaxy_tags:
  - debian
  - weechat

dependencies: []
