---
- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    cache_valid_time: 3600

- name: Set timezone
  community.general.timezone:
    name: Europe/Copenhagen
